# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c10cd697de00f2585ef631f3bb8f01389e1c08f273b275ae909451bfdcc893175542b4dbfc2a6c3daed649434cdca99ec4b1d48b514e36515053185b70a4622

test:
  secret_key_base: e173b13cc153a2c01ea05f670e4b6085be841321f938ec88472669f53de21ccf160350e7413f78674e700daa71bb7d21a05488c12ea372ff9c371e6daa2aa59e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
